export const headers = [
    { text: '번호', value: 'id' },
    { text: '주문번호', value: 'order_header_id' },
    { text: '주문상태', value: 'status' },
    { text: '상품코드', value: 'itemCode' },
    { text: '상품명', value: 'itemName' },
    { text: '단위', value: 'unit' },
    { text: '수량', value: 'quantity' },
    { text: '매입단가', value: 'purchase_price' },
    { text: '판매가', value: 'sales_price' },
    { text: '최종판매가', value: 'price_final' },
    { text: '마진률', value: 'margin_rate' },
    { text: '판매사원', value: 'member_id' },
    { text: '주문일자', value: 'order_date' },
    { text: '납품요청일자', value: 'request_date' },
    { text: '납품확정일자', value: 'accept_date' },
];

export const itemheaders = [
    { text: '번호', value: 'id' },
    { text: '상품코드', value: 'itemCode' },
    { text: '상품명', value: 'itemName' },
    { text: '단위', value: 'unit' },
    { text: '스펙', value: 'specs' },
    { text: '상태', value: 'itemStatus' },
];

export const items = [
    {
        id: '1',
        order_header_id: '12412',
        status: '승인 요청',
        item_code: '1245215',
        name: '뱅엔울룹슨 스페셜',
        unit: '1',
        quantity: '24,000',
        purchase_price: '234,000',
        sales_price: '749,000',
        price_final: '549,000',
        margin_rate: '20%',
        member_id: '박원일',
        order_date: '2024.02.28.',
        request_date: '2024.05.04.',
        accept_date: '2024.03.28.',
    },
    {
        id: '2',
        order_header_id: '12412',
        status: '승인 요청',
        item_code: '1245215',
        name: '뱅엔울룹슨 스페셜',
        unit: '1',
        quantity: '24,000',
        purchase_price: '234,000',
        sales_price: '749,000',
        price_final: '549,000',
        margin_rate: '20%',
        member_id: '박원일',
        order_date: '2024.02.28.',
        request_date: '2024.05.04.',
        accept_date: '2024.03.28.',
    },
    {
        id: '3',
        order_header_id: '12412',
        status: '승인 요청',
        item_code: '1245215',
        name: '뱅엔울룹슨 스페셜',
        unit: '1',
        quantity: '24,000',
        purchase_price: '234,000',
        sales_price: '749,000',
        price_final: '549,000',
        margin_rate: '20%',
        member_id: '박원일',
        order_date: '2024.02.28.',
        request_date: '2024.05.04.',
        accept_date: '2024.03.28.',
    },
    {
        id: '4',
        order_header_id: '12412',
        status: '승인 요청',
        item_code: '1245215',
        name: '뱅엔울룹슨 스페셜',
        unit: '1',
        quantity: '24,000',
        purchase_price: '234,000',
        sales_price: '749,000',
        price_final: '549,000',
        margin_rate: '20%',
        member_id: '박원일',
        order_date: '2024.02.28.',
        request_date: '2024.05.04.',
        accept_date: '2024.03.28.',
    },
];